/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1-jre")
    implementation("com.google.code.gson:gson:2.8.7")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
}

application {
    // Define the main class for the application.
    mainClass.set("gradle.demo.App")
}
