/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // deserialisasi data JSON dari Webservice
        try {
            String jsonWeb = getJson("https://api.github.com/users/petanikode");
            Gson gson = new Gson();
            GithubUser gitUser = gson.fromJson(jsonWeb, GithubUser.class);
            
            System.out.println("Hasil deserialisasi dari Webservice: ");
            System.out.println(gitUser.name);
            System.out.println(gitUser.email);
            System.out.println(gitUser.blog);
            System.out.println(gitUser.location);
            System.out.println(gitUser.html_url);
        } catch (Exception e) {
            System.out.println("Terjadi masalah: " + e.getMessage());
        }
    }
    public static String getJson(String url) throws Exception {

        HttpClient client = new DefaultHttpClient();
        HttpGet request = new HttpGet(url);

        // add request header
        request.addHeader("User-Agent", "Mozilla/5.0");

        HttpResponse response = client.execute(request);

        System.out.println("\nSending 'GET' request to URL : " + url);
        System.out.println("Response Code : "
                + response.getStatusLine().getStatusCode());

        BufferedReader rd = new BufferedReader(
                new InputStreamReader(response.getEntity().getContent()));

        StringBuffer result = new StringBuffer();
        String line = "";
        while ((line = rd.readLine()) != null) {
            result.append(line);
        }

        return result.toString();

    }
}
